### PR TITLE
#103 fix  server forgot password server sends new password 

### LINKED ISSUE #103: Server: Forgot password server sends new password
The server is given an email and sends it a new random and secure password

### PR DESCRIPTION
**Pull request by johannesfbraun**
create link first:
Patch:
https://localhost:3030/auth/forgot-password
Header:
Referer: http://localhost:3000/#/login
body(json):
{
    "email": "w.luft@studentische-beratung.de"
}

Then Update the PW:
Patch:
https://localhost:3030/auth//reset-forgot-password
Header:
Referer: http://localhost:3000/#/login
body(json):
{
    "email": "w.luft@studentische-beratung.de",
    "key":"$2a$10$jbDm3.DbNHVQGyRYNPWBYe9cBUr95BPygfdoB8M2YqBeUz23T6x4u",
    "newPassword":"s3cre7"
}
closes #103

### CODE REVIEW

File: server/src/global/auth/authController.ts [hunk 1]
```diff
@@ -167,6 +168,176 @@ export const retrieveUserData = (req: Request, res: Response) => {
...
+  const name = String(req.body.email).split("@")[0];
+  // Create a token
+  const plaintextToken = req.body.email.concat(date.getTime());
+  // Create a hash from the token
+  bcrypt.genSalt(10, (_err, salt) => {
+    bcrypt.hash(plaintextToken, salt, (_, hash) => {
+      // Check if email is valid
+      sleepRandomly(300, 400);
+      database
+        .query(
```
Comment (Prschmidt) [inline server/src/global/auth/authController.ts:188]: Test

**Review by Prschmidt — COMMENTED** [review]
Test

File: server/src/global/auth/authController.ts [hunk 2]
```diff
@@ -167,6 +168,176 @@ export const retrieveUserData = (req: Request, res: Response) => {
...
+  database
+    .query(
+      `SELECT mitglied_jbt_email, DATEDIFF(datum, ?) AS datediff, token FROM passwort_reset
+    WHERE mitglied_jbt_email = ?
+    AND token = ?`,
+      [date, req.body.email, req.body.key]
+    )
+    .then((result: authTypes.GetEmailDateTokenToVerifyValidity[]) => {
+      console.log(result[0].datediff);
+      if (result.length !== 0) {
```
Comment (LennartRukower) [inline server/src/global/auth/authController.ts:291]: Please reverse the if check such that if length is 0 send 200 status code.
Doing this only indents the res.status(200).send() and makes the code more readable.

File: server/src/global/auth/authController.ts [hunk 3]
```diff
@@ -167,6 +168,176 @@ export const retrieveUserData = (req: Request, res: Response) => {
...
+        // Check if the entry is older then five days
+        if (result[0].datediff < 5) {
```
Comment (LennartRukower) [inline server/src/global/auth/authController.ts:293]: Please reverse the if check such that if dateDiff is smaller or equal to 5 send 200 status code.
Doing this only indents the res.status(200).send() and makes the code more readable.

File: server/src/global/auth/authController.ts (hunk 2 above)
Comment (LennartRukower) [reply server/src/global/auth/authController.ts:291]: After the `res.status(200).send()` you can use a `return;` such that you do not need an else block.

File: server/src/global/auth/authController.ts (hunk 3 above)
Comment (LennartRukower) [reply server/src/global/auth/authController.ts:293]: After the `res.status(200).send()` you can use a `return;` such that you do not need an else block.

**Review by LennartRukower — CHANGES_REQUESTED** [review]
Nice work!
I did not check the functionality yet, but I have a few small suggestions on my side.

File: server/src/global/auth/authController.ts (hunk 2 above)
Comment (johannesfbraun) [reply server/src/global/auth/authController.ts:291]: I personally find it more complicated the way you propose it, as having a res.status(200).send() disrupts the logical progression for me.

File: server/src/global/auth/authController.ts (hunk 3 above)
Comment (johannesfbraun) [reply server/src/global/auth/authController.ts:293]: I personally find it more complicated the way you propose it, as having a `res.status(200).send()` disrupts the logical progression for me.

Comment (johannesfbraun) [reply server/src/global/auth/authController.ts:293]: For me the way i did it is more logical, as i have the complete yes path as one and afterwards the no paths.

File: server/src/global/auth/authController.ts [hunk 4]
```diff
@@ -167,6 +168,176 @@ export const retrieveUserData = (req: Request, res: Response) => {
...
+                // Insert the values into the passwort_reset table
+                database
+                  .query(
+                    `INSERT INTO passwort_reset (mitglied_jbt_email, salt, token)
+                    VALUES (?, ?, ?)`,
+                    [req.body.email, salt, hash]
+                  )
+                  .then(() => {
+                    // Send email with correct URL to usermail
+                    const transport = nodemailer.createTransport({
```
[the remark this answers is not in the document]
Comment (LennartRukower) [reply server/src/global/auth/authController.ts:213]: @johannesfbraun, are you going to resolve this issue or do you not agree with me?

File: server/src/global/auth/authController.ts [hunk 5]
```diff
@@ -167,6 +168,176 @@ export const retrieveUserData = (req: Request, res: Response) => {
...
+                      host: "studentische-beratung.de",
+                      port: 465,
+                      auth: {
+                        user: "mdbpasswortreset@studentische-beratung.de", // Email
+                        pass: "pQam721?", // PW
```
[the remark this answers is not in the document]
Comment (LennartRukower) [reply server/src/global/auth/authController.ts:218]: @johannesfbraun, are you going to resolve this issue or do you not agree with me?

**Review by LennartRukower — CHANGES_REQUESTED** [review]
Good job resolving some of my issues!
But there are two unresolved issues of mine still open.

File: server/src/global/auth/authController.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (johannesfbraun) [reply server/src/global/auth/authController.ts:218]: No I totally agree!

File: server/src/global/auth/authController.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (johannesfbraun) [reply server/src/global/auth/authController.ts:213]: I an not sure about this, as most of this would be different for each sent mail. Hence, I think the modularity and reusability would be marginal. But tell me if you disagree :)

[the remark this answers is not in the document]
Comment (JanMueller31) [reply server/src/global/auth/authController.ts:218]: Added this as a todo the transport should be placed in a separate file.

**Review by JanMueller31 — APPROVED** [review]

File: server/package.json [hunk 6]
```diff
@@ -15,9 +15,10 @@
     "csrf": "^3.1.0",
     "dotenv": "^8.2.0",
     "express": "^4.18.2",
-    "jsonwebtoken": "^9.0.0",
+    "jsonwebtoken": "^8.5.1",
```
[the remark this answers is not in the document]
Comment (JanMueller31) [reply server/package.json]: changed to 9.0.0
